server:
   port: 0

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      #&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1/snacknet?useSSL=false
      username: root
      password: syc123456
#或者driver-class-name: com.mysql.jdbc.Driver
   jackson:
      date-format: yyyy-MM-dd
      time-zone: GMT+8
#相同的配置节点只能出现一次
#邮件服务器配置(springboot 的配置项)
   mail:
      #邮箱服务器地址
    host: smtp.qq.com
      #用户名
    username: 1021634295@qq.com   
    password: kbjpwupimrjrbegj
    default-encoding: UTF-8  
   mvc:
      view:
       prefix: /WEB-INF/alipay/
       suffix: .jsp
#以谁来发邮件
mail:
   from:
      addr: 1021634295@qq.com
logging:
   level:
      com.yc.sn: debug